spring:
  application:
    name: transporte-backend
  profiles:
    active: dev
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
